name: code_verifier
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  vm_service: ^7.1.1
  quiver: ^3.1.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.0
